pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - status-success=Sider
      - status-success=Semantic Pull Request
      - status-success=Codacy Static Code Analysis
      - status-success=Travis CI - Pull Request
      - status-success=security/snyk (Bloomstack)
      - label!=Don't Merge
      - label!=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic squash on CI success and review
    conditions:
      - status-success=Sider
      - status-success=Codacy Static Code Analysis
      - status-success=Travis CI - Pull Request
      - status-success=security/snyk (Bloomstack)
      - label!=Don't Merge
      - label=squash
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
